In [2]:
from array import array
my_array = array('i',[1,2,3,4,5])


In [3]:
my_array

array('i', [1, 2, 3, 4, 5])

In [5]:
import numpy as np
arr = np.array([1,2,3,4])

In [7]:
arr

array([1, 2, 3, 4])

In [8]:
type(arr)

numpy.ndarray

In [9]:
arr.ndim

1

In [10]:
arr.dtype

dtype('int32')

In [12]:
array_new = np.array([1,2,3,4,5,6])
array_new + 3

array([4, 5, 6, 7, 8, 9])

In [13]:
type(array_new)

numpy.ndarray

In [15]:
my_numpy_arr = np.array([1,2,3,4,5])


In [16]:
my_numpy_arr

array([1, 2, 3, 4, 5])

In [17]:
new_arr = my_numpy_arr * 3

In [18]:
new_arr

array([ 3,  6,  9, 12, 15])

In [20]:
new_arr > 5

array([False,  True,  True,  True,  True])

In [24]:
arr_2d = np.array([[0,1,2,3],[4,5,6,7]])


In [25]:
arr_2d * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14]])

In [27]:
arr_3d = np.array([[1,2,3],[4,5,6],[7,8,9]]) 

In [28]:
arr_3d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
arr_3d * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [30]:
arr_3d + 2

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [32]:
import pandas as pd
data = pd.read_csv("tit.csv")

In [33]:
data

Unnamed: 0  survived  pclass     sex   age  sibsp  parch     fare  \
0             0         0       3    male  22.0      1      0   7.2500   
1             1         1       1  female  38.0      1      0  71.2833   
2             2         1       3  female  26.0      0      0   7.9250   
3             3         1       1  female  35.0      1      0  53.1000   
4             4         0       3    male  35.0      0      0   8.0500   
..          ...       ...     ...     ...   ...    ...    ...      ...   
886         886         0       2    male  27.0      0      0  13.0000   
887         887         1       1  female  19.0      0      0  30.0000   
888         888         0       3  female   NaN      1      2  23.4500   
889         889         1       1    male  26.0      0      0  30.0000   
890         890         0       3    male  32.0      0      0   7.7500   

    embarked   class    who  adult_male deck  embark_town alive  alone  
0          S   Third    man        True  NaN  Southampton    no  False  
1          C   First  woman       False    C    Cherbourg   yes  False  
2          S   Third  woman       False  NaN  Southampton   yes   True  
3          S   First  woman       False    C  Southampton   yes  False  
4          S   Third    man        True  NaN  Southampton    no   True  
..       ...     ...    ...         ...  ...          ...   ...    ...  
886        S  Second    man        True  NaN  Southampton    no   True  
887        S   First  woman       False    B  Southampton   yes   True  
888        S   Third  woman       False  NaN  Southampton    no  False  
889        C   First    man        True    C    Cherbourg   yes   True  
890        Q   Third    man        True  NaN   Queenstown    no   True  

[891 rows x 16 columns]

In [34]:
list1 = [1,2,3,4]
array_from_list = np.array(list1)

In [35]:
array_from_list

array([1, 2, 3, 4])

In [36]:
list1

[1, 2, 3, 4]

In [37]:
array_from_list.dtype

dtype('int32')

In [38]:
type(array_from_list)

numpy.ndarray