In [2]:
import numpy as np
a33 = np.ones((3,4))

a33

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [3]:
type(a33)

numpy.ndarray

In [9]:
a44 = np.zeros((2,4))

In [10]:
a44

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
type(a44)

numpy.ndarray

In [12]:
identity_mat = np.eye(3)

In [13]:
identity_mat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
identity_mat1 = np.eye(2)

In [16]:
identity_mat1

array([[1., 0.],
       [0., 1.]])

In [20]:
lists = [1,2,3,4]
np.array(lists,dtype=np.int32)


array([1, 2, 3, 4])

In [23]:
int_array = np.array([1,2,3],dtype=np.int32)
float_array = np.array([0.1,0.2,0.3],dtype=np.float64)

In [24]:
int_array

array([1, 2, 3])

In [25]:
float_array

array([0.1, 0.2, 0.3])

In [26]:
linspace_array_1 = np.linspace(0,10,6)
linspace_array_1

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [27]:
# linspace arrays
linspace_array_2 = np.linspace(0,10,6)
linspace_array_2

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [29]:
# random arrays
random_array = np.random.rand(4,4)
random_array

array([[0.35448928, 0.89255881, 0.79392521, 0.4419399 ],
       [0.85950616, 0.05594201, 0.51528699, 0.85979787],
       [0.91894771, 0.06883881, 0.0090885 , 0.88181365],
       [0.51355143, 0.96992036, 0.47978821, 0.73168255]])

In [31]:
#  basic indexing
arr = np.array([10,20,30,40])
print(arr[0])
print(arr[1])
print(arr[-1])

10
20
40


In [32]:
matrix = np.array([[1,2,3],[4,5,6]])
matrix[0,1]

2

In [33]:
matrix[1,2]

6

In [36]:
matrix[1,1]

5

In [40]:
# array slicing [start]:end:step]
arr = np.array([10,20,30,40,50])
print(arr[1:4])
print(arr[ :3])
print(arr[ ::2])
print(arr[ ::-1])

[20 30 40]
[10 20 30]
[10 30 50]
[50 40 30 20 10]


In [57]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
mat[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [81]:
mat[2:3,1:2]

array([[8]])

In [50]:
# view
a = np.array([1,2,3,4])
b = a[1:3]

In [51]:
b

array([2, 3])

In [52]:
a

array([1, 2, 3, 4])

In [54]:
b[0] = 99
b

array([99,  3])

In [55]:
a


array([ 1, 99,  3,  4])

In [63]:
# copy()
a = np.array([1,2,3,4])
b = a[1:3].copy()
b[0] =99
print(a)

[1 2 3 4]


In [66]:
# shape
arr = np.array([[1,2,3],[4,5,6]])
arr.shape

(2, 3)

In [67]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr.shape

(3, 3)

In [69]:
# arange
a = np.arange(12)

In [70]:
a 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [71]:
# reshape
b = a.reshape(3,4)

In [72]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [73]:
b1 = a.reshape(12,1)

In [74]:
b1

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [75]:
b2 = a.reshape(2,6)

In [76]:
b2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [79]:
# transpose
b2.transpose()

array([[ 0,  6],
       [ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11]])