In [1]:
# random numbers
import numpy as np

uniform = np.random.rand(3,3)
uniform

array([[0.03634922, 0.1358464 , 0.14376764],
       [0.36906402, 0.79601365, 0.59469384],
       [0.56475833, 0.47135362, 0.64195841]])

In [2]:
normal = np.random.randn(3,3)
normal

array([[ 0.46213415,  0.91272779, -0.32519768],
       [-0.22950258,  0.4400283 , -0.04751426],
       [-2.04741575, -0.56270432, -0.73904963]])

In [3]:
#searching in arrays
arr = np.array([1,2,3,4,5])
np.where(arr>3)

(array([3, 4], dtype=int64),)

In [4]:
np.where(arr<=2)

(array([0, 1], dtype=int64),)

In [6]:
#argmax() largest index will be returned
arr = np.array([1,2,3,4,5])
np.argmax(arr)

4

In [7]:
#argmin()
# min index will be returned
np.argmin(arr)

0

In [8]:
#searchsorted() returns the index element can be inserted in sorted array
sorted_arr = np.array([1,3,5,7])
np.searchsorted(sorted_arr,6)


3

In [9]:
np.searchsorted(sorted_arr,100)

4

In [10]:
# extract() extract values 
arr = np.array([1,2,3,4,5])
np.extract(arr>3,arr)


array([4, 5])

In [11]:
print("extract >2", np.extract(arr>2,arr))

extract >2 [3 4 5]


In [13]:
# transpose matrix

matrix = [[1,1,1,1,1],[2,2,2,2,2]]
np.transpose(matrix)

array([[1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2]])

In [14]:
#mean value
arr = np.array([1,2,3,4,5])
print("the mean value ",np.mean(arr))

the mean value  3.0


In [16]:
arr1 = np.array([1,2,3,4,5,6])
np.mean(arr1)

3.5

In [17]:
#splitting arrays
#equal parts split

arr = np.array([1,2,3,4,5,6])
np.split(arr,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [18]:
#split at specific position
np.split(arr,[1,4])

[array([1]), array([2, 3, 4]), array([5, 6])]

In [19]:
# split along row
matrix = np.array([[1,2,3],[4,5,6]])
np.split(matrix,3,axis=1)

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

In [23]:
# split along column
np.split(matrix,2,axis=0)

[array([[1, 2, 3]]), array([[4, 5, 6]])]