In [16]:
# joining

import numpy as np
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[1,1]])
np.concatenate((arr1, arr2), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [1, 1]])

In [17]:
np.concatenate((arr1, arr2), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 1, 1]])

In [13]:
# vstack
arr3 = np.array([1,2,3])
arr4 = np.array([4,5,6])
np.vstack((arr3,arr4))

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
#hstack
np.hstack((arr3,arr4))

array([1, 2, 3, 4, 5, 6])

In [21]:
# boolen indexing

arr = np.array([1,2,3,4,5,6])
mask = arr>3
mask

array([False, False, False,  True,  True,  True])

In [22]:
filtered = arr[mask]
print("filtered element i,e greater than 3 is : ",filtered)

filtered element i,e greater than 3 is :  [4 5 6]


In [23]:
#using and and or

arr = np.array([1,2,3,4,5,6])
(arr>2) & (arr<6)

array([False, False,  True,  True,  True, False])

In [24]:
arr[(arr>2) & (arr<6)]

array([3, 4, 5])

In [25]:
arr[(arr<=3) | (arr>5)]

array([1, 2, 3, 6])

In [26]:
# filtering 2d array

matrix = np.array([[10,15,20],[25,30,35]])
print("values>20:",matrix[matrix>20])

values>20: [25 30 35]


In [50]:
#first 15 natural numbers
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
# extract even numbers
arr[arr%2==0]


array([ 2,  4,  6,  8, 10, 12, 14])

In [51]:
# extract divisible by 3
arr[arr%3==0]

array([ 3,  6,  9, 12, 15])

In [58]:
#temperatures
temp = np.array([22.5,25.6,21.4,29.9,18.6,23.1,27])
# temperature greater than 24
temp[temp>24]

array([25.6, 29.9, 27. ])

In [62]:
# temperature between 20 and 26
temp[(temp>20) & (temp<26)]

array([22.5, 25.6, 21.4, 23.1])

In [57]:
# prices extract prices above 500
prices = np.array([250,499,520,310,800,999,450,720])
prices[prices>500]

array([520, 800, 999, 720])